# Generated by Django 2.0.2 on 2019-04-02 19:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('sizes', models.CharField(choices=[('small', 'SMALL'), ('large', 'LARGE'), ('extra-large', 'E-LARGE')], default='small', max_length=100)),
                ('colors', models.CharField(choices=[('green', 'GREEN'), ('red', 'RED'), ('black', 'BLACK'), ('blue', 'BLUE')], default='green', max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('product_img', models.ImageField(blank=True, default='default.jpg', upload_to='')),
            ],
        ),
    ]
